{{- range $serviceName, $serviceConfig := .Values.microservices }}
{{- if $serviceConfig.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arif-platform.fullname" $ }}-{{ $serviceName | kebabcase }}
  labels:
    {{- include "arif-platform.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName | kebabcase }}
spec:
  replicas: {{ $serviceConfig.replicaCount | default 2 }}
  selector:
    matchLabels:
      {{- include "arif-platform.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $serviceName | kebabcase }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") $ | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") $ | sha256sum }}
        {{- with $.Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "arif-platform.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ $serviceName | kebabcase }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "arif-platform.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $serviceName | kebabcase }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.image.registry }}/{{ $serviceConfig.image.repository }}:{{ $serviceConfig.image.tag | default $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:5000"
          envFrom:
            - configMapRef:
                name: {{ include "arif-platform.fullname" $ }}-config
            - secretRef:
                name: {{ include "arif-platform.fullname" $ }}-secrets
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
          resources:
            {{- toYaml $serviceConfig.resources | nindent 12 }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
