apiVersion: v1
kind: Secret
metadata:
  name: {{ include "arif-platform.fullname" . }}-secrets
  labels:
    {{- include "arif-platform.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET_KEY: {{ .Values.security.jwt.secretKey | b64enc | quote }}
  {{- if .Values.sqlserver.enabled }}
  SA_PASSWORD: {{ .Values.sqlserver.sapassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.integrations.openai.apiKey }}
  OPENAI_API_KEY: {{ .Values.integrations.openai.apiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.integrations.azure.openai.apiKey }}
  AZURE_OPENAI_API_KEY: {{ .Values.integrations.azure.openai.apiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.integrations.twilio.authToken }}
  TWILIO_AUTH_TOKEN: {{ .Values.integrations.twilio.authToken | b64enc | quote }}
  {{- end }}
  {{- if .Values.integrations.facebook.appSecret }}
  FACEBOOK_APP_SECRET: {{ .Values.integrations.facebook.appSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.integrations.slack.botToken }}
  SLACK_BOT_TOKEN: {{ .Values.integrations.slack.botToken | b64enc | quote }}
  {{- end }}
  {{- if .Values.integrations.salesforce.clientSecret }}
  SALESFORCE_CLIENT_SECRET: {{ .Values.integrations.salesforce.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.integrations.hubspot.apiKey }}
  HUBSPOT_API_KEY: {{ .Values.integrations.hubspot.apiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.integrations.stripe.secretKey }}
  STRIPE_SECRET_KEY: {{ .Values.integrations.stripe.secretKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.integrations.smtp.password }}
  SMTP_PASSWORD: {{ .Values.integrations.smtp.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.integrations.firebase.serverKey }}
  FIREBASE_SERVER_KEY: {{ .Values.integrations.firebase.serverKey | b64enc | quote }}
  {{- end }}
