{{- range $serviceName, $serviceConfig := .Values.microservices }}
{{- if $serviceConfig.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "arif-platform.fullname" $ }}-{{ $serviceName | kebabcase }}
  labels:
    {{- include "arif-platform.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName | kebabcase }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $serviceConfig.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "arif-platform.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName | kebabcase }}
{{- end }}
{{- end }}

{{- if .Values.apiGateway.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "arif-platform.fullname" . }}-api-gateway
  labels:
    {{- include "arif-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
spec:
  type: {{ .Values.apiGateway.service.type }}
  ports:
    - port: {{ .Values.apiGateway.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "arif-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
{{- end }}
