apiVersion: v1
kind: ConfigMap
metadata:
  name: arif-platform-config
  namespace: arif-platform
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  JWT__Issuer: "ArifPlatform"
  JWT__Audience: "ArifPlatformUsers"
  Redis__ConnectionString: "arif-redis:6379"
  ConnectionStrings__DefaultConnection: "Server=arif-sqlserver;Database=ArifPlatform;User Id=sa;Password=ArifPlatform2024!;TrustServerCertificate=true;"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: arif-platform-config-dev
  namespace: arif-platform-dev
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  JWT__Issuer: "ArifPlatform"
  JWT__Audience: "ArifPlatformUsers"
  Redis__ConnectionString: "arif-redis:6379"
  ConnectionStrings__DefaultConnection: "Server=arif-sqlserver;Database=ArifPlatform;User Id=sa;Password=ArifPlatform2024!;TrustServerCertificate=true;"
