apiVersion: v2
name: arif-platform
description: A Helm chart for Arif Generative AI Chatbot Platform
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - chatbot
  - ai
  - microservices
  - dotnet
  - arabic
home: https://github.com/arif-platform/arif-platform
sources:
  - https://github.com/arif-platform/arif-platform
maintainers:
  - name: Arif Platform Team
    email: support@arif-platform.com
dependencies:
  - name: redis
    version: "17.15.2"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: mssql-linux
    version: "0.11.2"
    repository: "https://charts.helm.sh/stable"
    condition: sqlserver.enabled
